name: Feature
description: New feature
title: "[New Feature]: "
labels: [feature, triage]
body:
- type: markdown
  attributes:
    value: |
      - Write a descriptive feature title above.
      - Search [open](https://github.com/My-Virtual-Worlds/MyAlchemy/issues?q=is%3Aopen+label%3Afeature+is%3Aissue) feature requests to ensure that the feature has not already been requested.

- type: textarea
  attributes:
    label: Environment
    description: About Alchemy Text
    placeholder: ex. Alchemy Test 7.1.3.240191747 (64bit) ...
  validations:
    required: true

- type: textarea
  attributes:
    label: Description
    description: What does this feature do? Why is it needed? Include screenshots to illustrate how it should function if possible!
  validations:
    required: true

- type: textarea
  attributes:
    label: Do other viewers use proposed feature?
    description: what other viewers, if any, use this feature currently? Please provide links to viewers using this feature for our review.
  validations:
    required: true