blank_issues_enabled: false
#contact_links:
#- name: 💬 Alchemy Viewer Discord
#  url: https://discordapp.com/invite/KugCgs6
#  about: Space for discussing and reviewing user-impacting bug reports and feature requests.
